### PR TITLE
Re introduced the legendary page

### PR DESCRIPTION
**Pull request by Brosssh**
Now it does NOT redirect anymore to another site (https://legendary-study.netlify.app/), everything it's in the same site.

Carpet, please check if all the library are OK, I have some issue with some of these but while debugging they were all working so idk, maybe it was a visual issue on VSC. 
Also check what actions are needed to the build on netifly, since it's a new page i'm not sure what action are needed,

New reports are loaded daily at 6 AM UTC

### CODE REVIEW

**Comment by carpetsage** [comment]
I pushed some changes to fix issues with pnpm and missing dependencies and then the merge conflcit that came from that.

Once I fixed all that I still get some weird error when building with typescript type checking 

src/views/Diff.vue:20:16 - error TS2339: Property 'default' does not exist on type '{}'.

20     <template #default>



 even without type checking it fails because it doesn't like the await getTimestampsReports() in src/reports.ts
 

`Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)`

**Comment by Brosssh** [comment]
Pretty sure the "top level await is not available" thing would just be solved by updating the node/typescript version. Will see if a workaround is doable since I guess that updating everything may be an issue for other stuff

**Comment by carpetsage** [comment]
This is using the latest typescript already and running in browsers not in node. That's actually the problem here. Top level await is fine for node but not for browsers

**Comment by Brosssh** [comment]
All of the common browsers allow await at top level (see image) so i've just told typescript to enable it, please tell me if you know how to fix this, i've tried multiple things but the getTimestampsReports always end up expecting a Promise<>. It should be fixed, but on some old browser it may not work

image

**Comment by carpetsage** [comment]
I can get it to fastbuild to work now after moving some stuff to public/static so I can actually run it now and it looks fine.

 Still has the same 
`Property 'default' does not exist on type '{}'.`
with the full type checking on and I don't really have any idea why but I don't want to merge it and make all my builds start failing

**Comment by Brosssh** [comment]
Fine for me, thanks :)

**Pull request merged**
